// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/nucladb.proto

package nucladbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DistanceMetric int32

const (
	DistanceMetric_DISTANCE_METRIC_UNSPECIFIED DistanceMetric = 0
	DistanceMetric_DISTANCE_METRIC_COSINE      DistanceMetric = 1
	DistanceMetric_DISTANCE_METRIC_L2          DistanceMetric = 2
	DistanceMetric_DISTANCE_METRIC_DOT         DistanceMetric = 3
)

// Enum value maps for DistanceMetric.
var (
	DistanceMetric_name = map[int32]string{
		0: "DISTANCE_METRIC_UNSPECIFIED",
		1: "DISTANCE_METRIC_COSINE",
		2: "DISTANCE_METRIC_L2",
		3: "DISTANCE_METRIC_DOT",
	}
	DistanceMetric_value = map[string]int32{
		"DISTANCE_METRIC_UNSPECIFIED": 0,
		"DISTANCE_METRIC_COSINE":      1,
		"DISTANCE_METRIC_L2":          2,
		"DISTANCE_METRIC_DOT":         3,
	}
)

func (x DistanceMetric) Enum() *DistanceMetric {
	p := new(DistanceMetric)
	*p = x
	return p
}

func (x DistanceMetric) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DistanceMetric) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_nucladb_proto_enumTypes[0].Descriptor()
}

func (DistanceMetric) Type() protoreflect.EnumType {
	return &file_proto_nucladb_proto_enumTypes[0]
}

func (x DistanceMetric) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DistanceMetric.Descriptor instead.
func (DistanceMetric) EnumDescriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{0}
}

// TenantQuota bounds one tenant's resource usage. A zero value for either
// field means unlimited.
type TenantQuota struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxVectors    int64                  `protobuf:"varint,1,opt,name=max_vectors,json=maxVectors,proto3" json:"max_vectors,omitempty"`
	MaxQps        float64                `protobuf:"fixed64,2,opt,name=max_qps,json=maxQps,proto3" json:"max_qps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantQuota) Reset() {
	*x = TenantQuota{}
	mi := &file_proto_nucladb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantQuota) ProtoMessage() {}

func (x *TenantQuota) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantQuota.ProtoReflect.Descriptor instead.
func (*TenantQuota) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{0}
}

func (x *TenantQuota) GetMaxVectors() int64 {
	if x != nil {
		return x.MaxVectors
	}
	return 0
}

func (x *TenantQuota) GetMaxQps() float64 {
	if x != nil {
		return x.MaxQps
	}
	return 0
}

type CreateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Quota         *TenantQuota           `protobuf:"bytes,2,opt,name=quota,proto3" json:"quota,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_proto_nucladb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateTenantRequest) GetQuota() *TenantQuota {
	if x != nil {
		return x.Quota
	}
	return nil
}

type CreateTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantResponse) Reset() {
	*x = CreateTenantResponse{}
	mi := &file_proto_nucladb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantResponse) ProtoMessage() {}

func (x *CreateTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantResponse.ProtoReflect.Descriptor instead.
func (*CreateTenantResponse) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{2}
}

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Values        []float32              `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_proto_nucladb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{3}
}

func (x *Vector) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Vector) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Vector) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        *Vector                `protobuf:"bytes,1,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_proto_nucladb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{4}
}

func (x *InsertRequest) GetVector() *Vector {
	if x != nil {
		return x.Vector
	}
	return nil
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_proto_nucladb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{5}
}

func (x *InsertResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BatchUpsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vectors       []*Vector              `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpsertRequest) Reset() {
	*x = BatchUpsertRequest{}
	mi := &file_proto_nucladb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpsertRequest) ProtoMessage() {}

func (x *BatchUpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpsertRequest.ProtoReflect.Descriptor instead.
func (*BatchUpsertRequest) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{6}
}

func (x *BatchUpsertRequest) GetVectors() []*Vector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type BatchUpsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upserted      int64                  `protobuf:"varint,1,opt,name=upserted,proto3" json:"upserted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpsertResponse) Reset() {
	*x = BatchUpsertResponse{}
	mi := &file_proto_nucladb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpsertResponse) ProtoMessage() {}

func (x *BatchUpsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpsertResponse.ProtoReflect.Descriptor instead.
func (*BatchUpsertResponse) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{7}
}

func (x *BatchUpsertResponse) GetUpserted() int64 {
	if x != nil {
		return x.Upserted
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_nucladb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_nucladb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type MetadataFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataFilter) Reset() {
	*x = MetadataFilter{}
	mi := &file_proto_nucladb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataFilter) ProtoMessage() {}

func (x *MetadataFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataFilter.ProtoReflect.Descriptor instead.
func (*MetadataFilter) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{10}
}

func (x *MetadataFilter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetadataFilter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         []float32              `protobuf:"fixed32,1,rep,packed,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Metric        DistanceMetric         `protobuf:"varint,3,opt,name=metric,proto3,enum=nucladb.v1.DistanceMetric" json:"metric,omitempty"`
	EfSearch      int32                  `protobuf:"varint,4,opt,name=ef_search,json=efSearch,proto3" json:"ef_search,omitempty"`
	Filters       []*MetadataFilter      `protobuf:"bytes,5,rep,name=filters,proto3" json:"filters,omitempty"`
	TenantId      string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_nucladb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{11}
}

func (x *SearchRequest) GetQuery() []float32 {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetMetric() DistanceMetric {
	if x != nil {
		return x.Metric
	}
	return DistanceMetric_DISTANCE_METRIC_UNSPECIFIED
}

func (x *SearchRequest) GetEfSearch() int32 {
	if x != nil {
		return x.EfSearch
	}
	return 0
}

func (x *SearchRequest) GetFilters() []*MetadataFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SearchRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ScoredVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoredVector) Reset() {
	*x = ScoredVector{}
	mi := &file_proto_nucladb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredVector) ProtoMessage() {}

func (x *ScoredVector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredVector.ProtoReflect.Descriptor instead.
func (*ScoredVector) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{12}
}

func (x *ScoredVector) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScoredVector) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoredVector) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*ScoredVector        `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_nucladb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{13}
}

func (x *SearchResponse) GetMatches() []*ScoredVector {
	if x != nil {
		return x.Matches
	}
	return nil
}

var File_proto_nucladb_proto protoreflect.FileDescriptor

const file_proto_nucladb_proto_rawDesc = "" +
	"\n" +
	"\x13proto/nucladb.proto\x12\n" +
	"nucladb.v1\"G\n" +
	"\vTenantQuota\x12\x1f\n" +
	"\vmax_vectors\x18\x01 \x01(\x03R\n" +
	"maxVectors\x12\x17\n" +
	"\amax_qps\x18\x02 \x01(\x01R\x06maxQps\"a\n" +
	"\x13CreateTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12-\n" +
	"\x05quota\x18\x02 \x01(\v2\x17.nucladb.v1.TenantQuotaR\x05quota\"\x16\n" +
	"\x14CreateTenantResponse\"\xc8\x01\n" +
	"\x06Vector\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x02R\x06values\x12<\n" +
	"\bmetadata\x18\x03 \x03(\v2 .nucladb.v1.Vector.MetadataEntryR\bmetadata\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\rInsertRequest\x12*\n" +
	"\x06vector\x18\x01 \x01(\v2\x12.nucladb.v1.VectorR\x06vector\" \n" +
	"\x0eInsertResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x12BatchUpsertRequest\x12,\n" +
	"\avectors\x18\x01 \x03(\v2\x12.nucladb.v1.VectorR\avectors\"1\n" +
	"\x13BatchUpsertResponse\x12\x1a\n" +
	"\bupserted\x18\x01 \x01(\x03R\bupserted\"<\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"8\n" +
	"\x0eMetadataFilter\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xde\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x03(\x02R\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x122\n" +
	"\x06metric\x18\x03 \x01(\x0e2\x1a.nucladb.v1.DistanceMetricR\x06metric\x12\x1b\n" +
	"\tef_search\x18\x04 \x01(\x05R\befSearch\x124\n" +
	"\afilters\x18\x05 \x03(\v2\x1a.nucladb.v1.MetadataFilterR\afilters\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\"\xb5\x01\n" +
	"\fScoredVector\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12B\n" +
	"\bmetadata\x18\x03 \x03(\v2&.nucladb.v1.ScoredVector.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x0eSearchResponse\x122\n" +
	"\amatches\x18\x01 \x03(\v2\x18.nucladb.v1.ScoredVectorR\amatches*~\n" +
	"\x0eDistanceMetric\x12\x1f\n" +
	"\x1bDISTANCE_METRIC_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DISTANCE_METRIC_COSINE\x10\x01\x12\x16\n" +
	"\x12DISTANCE_METRIC_L2\x10\x02\x12\x17\n" +
	"\x13DISTANCE_METRIC_DOT\x10\x032\xef\x02\n" +
	"\aNuclaDB\x12Q\n" +
	"\fCreateTenant\x12\x1f.nucladb.v1.CreateTenantRequest\x1a .nucladb.v1.CreateTenantResponse\x12?\n" +
	"\x06Insert\x12\x19.nucladb.v1.InsertRequest\x1a\x1a.nucladb.v1.InsertResponse\x12N\n" +
	"\vBatchUpsert\x12\x1e.nucladb.v1.BatchUpsertRequest\x1a\x1f.nucladb.v1.BatchUpsertResponse\x12?\n" +
	"\x06Delete\x12\x19.nucladb.v1.DeleteRequest\x1a\x1a.nucladb.v1.DeleteResponse\x12?\n" +
	"\x06Search\x12\x19.nucladb.v1.SearchRequest\x1a\x1a.nucladb.v1.SearchResponseB0Z.github.com/Rakshit-gen/nucladb/proto/nucladbv1b\x06proto3"

var (
	file_proto_nucladb_proto_rawDescOnce sync.Once
	file_proto_nucladb_proto_rawDescData []byte
)

func file_proto_nucladb_proto_rawDescGZIP() []byte {
	file_proto_nucladb_proto_rawDescOnce.Do(func() {
		file_proto_nucladb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_nucladb_proto_rawDesc), len(file_proto_nucladb_proto_rawDesc)))
	})
	return file_proto_nucladb_proto_rawDescData
}

var file_proto_nucladb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_nucladb_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_nucladb_proto_goTypes = []any{
	(DistanceMetric)(0),          // 0: nucladb.v1.DistanceMetric
	(*TenantQuota)(nil),          // 1: nucladb.v1.TenantQuota
	(*CreateTenantRequest)(nil),  // 2: nucladb.v1.CreateTenantRequest
	(*CreateTenantResponse)(nil), // 3: nucladb.v1.CreateTenantResponse
	(*Vector)(nil),               // 4: nucladb.v1.Vector
	(*InsertRequest)(nil),        // 5: nucladb.v1.InsertRequest
	(*InsertResponse)(nil),       // 6: nucladb.v1.InsertResponse
	(*BatchUpsertRequest)(nil),   // 7: nucladb.v1.BatchUpsertRequest
	(*BatchUpsertResponse)(nil),  // 8: nucladb.v1.BatchUpsertResponse
	(*DeleteRequest)(nil),        // 9: nucladb.v1.DeleteRequest
	(*DeleteResponse)(nil),       // 10: nucladb.v1.DeleteResponse
	(*MetadataFilter)(nil),       // 11: nucladb.v1.MetadataFilter
	(*SearchRequest)(nil),        // 12: nucladb.v1.SearchRequest
	(*ScoredVector)(nil),         // 13: nucladb.v1.ScoredVector
	(*SearchResponse)(nil),       // 14: nucladb.v1.SearchResponse
	nil,                          // 15: nucladb.v1.Vector.MetadataEntry
	nil,                          // 16: nucladb.v1.ScoredVector.MetadataEntry
}
var file_proto_nucladb_proto_depIdxs = []int32{
	1,  // 0: nucladb.v1.CreateTenantRequest.quota:type_name -> nucladb.v1.TenantQuota
	15, // 1: nucladb.v1.Vector.metadata:type_name -> nucladb.v1.Vector.MetadataEntry
	4,  // 2: nucladb.v1.InsertRequest.vector:type_name -> nucladb.v1.Vector
	4,  // 3: nucladb.v1.BatchUpsertRequest.vectors:type_name -> nucladb.v1.Vector
	0,  // 4: nucladb.v1.SearchRequest.metric:type_name -> nucladb.v1.DistanceMetric
	11, // 5: nucladb.v1.SearchRequest.filters:type_name -> nucladb.v1.MetadataFilter
	16, // 6: nucladb.v1.ScoredVector.metadata:type_name -> nucladb.v1.ScoredVector.MetadataEntry
	13, // 7: nucladb.v1.SearchResponse.matches:type_name -> nucladb.v1.ScoredVector
	2,  // 8: nucladb.v1.NuclaDB.CreateTenant:input_type -> nucladb.v1.CreateTenantRequest
	5,  // 9: nucladb.v1.NuclaDB.Insert:input_type -> nucladb.v1.InsertRequest
	7,  // 10: nucladb.v1.NuclaDB.BatchUpsert:input_type -> nucladb.v1.BatchUpsertRequest
	9,  // 11: nucladb.v1.NuclaDB.Delete:input_type -> nucladb.v1.DeleteRequest
	12, // 12: nucladb.v1.NuclaDB.Search:input_type -> nucladb.v1.SearchRequest
	3,  // 13: nucladb.v1.NuclaDB.CreateTenant:output_type -> nucladb.v1.CreateTenantResponse
	6,  // 14: nucladb.v1.NuclaDB.Insert:output_type -> nucladb.v1.InsertResponse
	8,  // 15: nucladb.v1.NuclaDB.BatchUpsert:output_type -> nucladb.v1.BatchUpsertResponse
	10, // 16: nucladb.v1.NuclaDB.Delete:output_type -> nucladb.v1.DeleteResponse
	14, // 17: nucladb.v1.NuclaDB.Search:output_type -> nucladb.v1.SearchResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_nucladb_proto_init() }
func file_proto_nucladb_proto_init() {
	if File_proto_nucladb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_nucladb_proto_rawDesc), len(file_proto_nucladb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_nucladb_proto_goTypes,
		DependencyIndexes: file_proto_nucladb_proto_depIdxs,
		EnumInfos:         file_proto_nucladb_proto_enumTypes,
		MessageInfos:      file_proto_nucladb_proto_msgTypes,
	}.Build()
	File_proto_nucladb_proto = out.File
	file_proto_nucladb_proto_goTypes = nil
	file_proto_nucladb_proto_depIdxs = nil
}
