// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/nucladb.proto

package nucladbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NuclaDB_CreateTenant_FullMethodName = "/nucladb.v1.NuclaDB/CreateTenant"
	NuclaDB_Insert_FullMethodName       = "/nucladb.v1.NuclaDB/Insert"
	NuclaDB_BatchUpsert_FullMethodName  = "/nucladb.v1.NuclaDB/BatchUpsert"
	NuclaDB_Delete_FullMethodName       = "/nucladb.v1.NuclaDB/Delete"
	NuclaDB_Search_FullMethodName       = "/nucladb.v1.NuclaDB/Search"
)

// NuclaDBClient is the client API for NuclaDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NuclaDB is a vector similarity search engine: insert vectors with an
// optional metadata payload, then search for the nearest neighbors of a
// query vector under a chosen distance metric.
//
// Every data RPC is tenant-scoped: each tenant_id gets an isolated index
// (its own graph, WAL, and snapshot files on disk), with an independent
// storage quota and request-rate limit. An empty tenant_id resolves to a
// reserved "default" tenant with no quota, so existing single-tenant
// usage needs no changes.
//
// REST is exposed separately via a hand-written gateway in
// internal/api/gateway rather than google.api.http annotations, to avoid
// vendoring the full googleapis proto tree for five routes.
type NuclaDBClient interface {
	CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*CreateTenantResponse, error)
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	BatchUpsert(ctx context.Context, in *BatchUpsertRequest, opts ...grpc.CallOption) (*BatchUpsertResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type nuclaDBClient struct {
	cc grpc.ClientConnInterface
}

func NewNuclaDBClient(cc grpc.ClientConnInterface) NuclaDBClient {
	return &nuclaDBClient{cc}
}

func (c *nuclaDBClient) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*CreateTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTenantResponse)
	err := c.cc.Invoke(ctx, NuclaDB_CreateTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nuclaDBClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, NuclaDB_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nuclaDBClient) BatchUpsert(ctx context.Context, in *BatchUpsertRequest, opts ...grpc.CallOption) (*BatchUpsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUpsertResponse)
	err := c.cc.Invoke(ctx, NuclaDB_BatchUpsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nuclaDBClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, NuclaDB_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nuclaDBClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, NuclaDB_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NuclaDBServer is the server API for NuclaDB service.
// All implementations must embed UnimplementedNuclaDBServer
// for forward compatibility.
//
// NuclaDB is a vector similarity search engine: insert vectors with an
// optional metadata payload, then search for the nearest neighbors of a
// query vector under a chosen distance metric.
//
// Every data RPC is tenant-scoped: each tenant_id gets an isolated index
// (its own graph, WAL, and snapshot files on disk), with an independent
// storage quota and request-rate limit. An empty tenant_id resolves to a
// reserved "default" tenant with no quota, so existing single-tenant
// usage needs no changes.
//
// REST is exposed separately via a hand-written gateway in
// internal/api/gateway rather than google.api.http annotations, to avoid
// vendoring the full googleapis proto tree for five routes.
type NuclaDBServer interface {
	CreateTenant(context.Context, *CreateTenantRequest) (*CreateTenantResponse, error)
	Insert(context.Context, *InsertRequest) (*InsertResponse, error)
	BatchUpsert(context.Context, *BatchUpsertRequest) (*BatchUpsertResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedNuclaDBServer()
}

// UnimplementedNuclaDBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNuclaDBServer struct{}

func (UnimplementedNuclaDBServer) CreateTenant(context.Context, *CreateTenantRequest) (*CreateTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTenant not implemented")
}
func (UnimplementedNuclaDBServer) Insert(context.Context, *InsertRequest) (*InsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedNuclaDBServer) BatchUpsert(context.Context, *BatchUpsertRequest) (*BatchUpsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchUpsert not implemented")
}
func (UnimplementedNuclaDBServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedNuclaDBServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedNuclaDBServer) mustEmbedUnimplementedNuclaDBServer() {}
func (UnimplementedNuclaDBServer) testEmbeddedByValue()                 {}

// UnsafeNuclaDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NuclaDBServer will
// result in compilation errors.
type UnsafeNuclaDBServer interface {
	mustEmbedUnimplementedNuclaDBServer()
}

func RegisterNuclaDBServer(s grpc.ServiceRegistrar, srv NuclaDBServer) {
	// If the following call panics, it indicates UnimplementedNuclaDBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NuclaDB_ServiceDesc, srv)
}

func _NuclaDB_CreateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NuclaDBServer).CreateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NuclaDB_CreateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NuclaDBServer).CreateTenant(ctx, req.(*CreateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NuclaDB_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NuclaDBServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NuclaDB_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NuclaDBServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NuclaDB_BatchUpsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NuclaDBServer).BatchUpsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NuclaDB_BatchUpsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NuclaDBServer).BatchUpsert(ctx, req.(*BatchUpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NuclaDB_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NuclaDBServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NuclaDB_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NuclaDBServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NuclaDB_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NuclaDBServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NuclaDB_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NuclaDBServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NuclaDB_ServiceDesc is the grpc.ServiceDesc for NuclaDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NuclaDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nucladb.v1.NuclaDB",
	HandlerType: (*NuclaDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTenant",
			Handler:    _NuclaDB_CreateTenant_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _NuclaDB_Insert_Handler,
		},
		{
			MethodName: "BatchUpsert",
			Handler:    _NuclaDB_BatchUpsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _NuclaDB_Delete_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _NuclaDB_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/nucladb.proto",
}
