// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/nucladb.proto

package nucladbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DistanceMetric int32

const (
	DistanceMetric_DISTANCE_METRIC_UNSPECIFIED DistanceMetric = 0
	DistanceMetric_DISTANCE_METRIC_COSINE      DistanceMetric = 1
	DistanceMetric_DISTANCE_METRIC_L2          DistanceMetric = 2
	DistanceMetric_DISTANCE_METRIC_DOT         DistanceMetric = 3
)

// Enum value maps for DistanceMetric.
var (
	DistanceMetric_name = map[int32]string{
		0: "DISTANCE_METRIC_UNSPECIFIED",
		1: "DISTANCE_METRIC_COSINE",
		2: "DISTANCE_METRIC_L2",
		3: "DISTANCE_METRIC_DOT",
	}
	DistanceMetric_value = map[string]int32{
		"DISTANCE_METRIC_UNSPECIFIED": 0,
		"DISTANCE_METRIC_COSINE":      1,
		"DISTANCE_METRIC_L2":          2,
		"DISTANCE_METRIC_DOT":         3,
	}
)

func (x DistanceMetric) Enum() *DistanceMetric {
	p := new(DistanceMetric)
	*p = x
	return p
}

func (x DistanceMetric) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DistanceMetric) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_nucladb_proto_enumTypes[0].Descriptor()
}

func (DistanceMetric) Type() protoreflect.EnumType {
	return &file_proto_nucladb_proto_enumTypes[0]
}

func (x DistanceMetric) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DistanceMetric.Descriptor instead.
func (DistanceMetric) EnumDescriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{0}
}

// FilterOp is how a MetadataFilter compares. The zero value is EQ, so a
// filter that sets only key and value is an equality check.
type FilterOp int32

const (
	FilterOp_FILTER_OP_EQ     FilterOp = 0
	FilterOp_FILTER_OP_NE     FilterOp = 1 // key missing, or value differs
	FilterOp_FILTER_OP_IN     FilterOp = 2 // value is one of values
	FilterOp_FILTER_OP_NOT_IN FilterOp = 3 // key missing, or value is none of values
	FilterOp_FILTER_OP_GT     FilterOp = 4 // numeric comparisons parse the stored value
	FilterOp_FILTER_OP_GTE    FilterOp = 5 // as a number; a non-number never matches
	FilterOp_FILTER_OP_LT     FilterOp = 6
	FilterOp_FILTER_OP_LTE    FilterOp = 7
	FilterOp_FILTER_OP_EXISTS FilterOp = 8 // key is present
)

// Enum value maps for FilterOp.
var (
	FilterOp_name = map[int32]string{
		0: "FILTER_OP_EQ",
		1: "FILTER_OP_NE",
		2: "FILTER_OP_IN",
		3: "FILTER_OP_NOT_IN",
		4: "FILTER_OP_GT",
		5: "FILTER_OP_GTE",
		6: "FILTER_OP_LT",
		7: "FILTER_OP_LTE",
		8: "FILTER_OP_EXISTS",
	}
	FilterOp_value = map[string]int32{
		"FILTER_OP_EQ":     0,
		"FILTER_OP_NE":     1,
		"FILTER_OP_IN":     2,
		"FILTER_OP_NOT_IN": 3,
		"FILTER_OP_GT":     4,
		"FILTER_OP_GTE":    5,
		"FILTER_OP_LT":     6,
		"FILTER_OP_LTE":    7,
		"FILTER_OP_EXISTS": 8,
	}
)

func (x FilterOp) Enum() *FilterOp {
	p := new(FilterOp)
	*p = x
	return p
}

func (x FilterOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterOp) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_nucladb_proto_enumTypes[1].Descriptor()
}

func (FilterOp) Type() protoreflect.EnumType {
	return &file_proto_nucladb_proto_enumTypes[1]
}

func (x FilterOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterOp.Descriptor instead.
func (FilterOp) EnumDescriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{1}
}

// TenantQuota bounds one tenant's resource usage. A zero value for either
// field means unlimited.
type TenantQuota struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxVectors    int64                  `protobuf:"varint,1,opt,name=max_vectors,json=maxVectors,proto3" json:"max_vectors,omitempty"`
	MaxQps        float64                `protobuf:"fixed64,2,opt,name=max_qps,json=maxQps,proto3" json:"max_qps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantQuota) Reset() {
	*x = TenantQuota{}
	mi := &file_proto_nucladb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantQuota) ProtoMessage() {}

func (x *TenantQuota) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantQuota.ProtoReflect.Descriptor instead.
func (*TenantQuota) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{0}
}

func (x *TenantQuota) GetMaxVectors() int64 {
	if x != nil {
		return x.MaxVectors
	}
	return 0
}

func (x *TenantQuota) GetMaxQps() float64 {
	if x != nil {
		return x.MaxQps
	}
	return 0
}

// dim and metric are fixed for the tenant's life. 0 and UNSPECIFIED take
// the server's defaults (its -dim and -metric flags).
type CreateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Quota         *TenantQuota           `protobuf:"bytes,2,opt,name=quota,proto3" json:"quota,omitempty"`
	Dim           int32                  `protobuf:"varint,3,opt,name=dim,proto3" json:"dim,omitempty"`
	Metric        DistanceMetric         `protobuf:"varint,4,opt,name=metric,proto3,enum=nucladb.v1.DistanceMetric" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_proto_nucladb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateTenantRequest) GetQuota() *TenantQuota {
	if x != nil {
		return x.Quota
	}
	return nil
}

func (x *CreateTenantRequest) GetDim() int32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *CreateTenantRequest) GetMetric() DistanceMetric {
	if x != nil {
		return x.Metric
	}
	return DistanceMetric_DISTANCE_METRIC_UNSPECIFIED
}

type CreateTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantResponse) Reset() {
	*x = CreateTenantResponse{}
	mi := &file_proto_nucladb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantResponse) ProtoMessage() {}

func (x *CreateTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantResponse.ProtoReflect.Descriptor instead.
func (*CreateTenantResponse) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{2}
}

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Values        []float32              `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_proto_nucladb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{3}
}

func (x *Vector) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Vector) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Vector) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        *Vector                `protobuf:"bytes,1,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_proto_nucladb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{4}
}

func (x *InsertRequest) GetVector() *Vector {
	if x != nil {
		return x.Vector
	}
	return nil
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_proto_nucladb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{5}
}

func (x *InsertResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BatchUpsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vectors       []*Vector              `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpsertRequest) Reset() {
	*x = BatchUpsertRequest{}
	mi := &file_proto_nucladb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpsertRequest) ProtoMessage() {}

func (x *BatchUpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpsertRequest.ProtoReflect.Descriptor instead.
func (*BatchUpsertRequest) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{6}
}

func (x *BatchUpsertRequest) GetVectors() []*Vector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type BatchUpsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upserted      int64                  `protobuf:"varint,1,opt,name=upserted,proto3" json:"upserted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpsertResponse) Reset() {
	*x = BatchUpsertResponse{}
	mi := &file_proto_nucladb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpsertResponse) ProtoMessage() {}

func (x *BatchUpsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpsertResponse.ProtoReflect.Descriptor instead.
func (*BatchUpsertResponse) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{7}
}

func (x *BatchUpsertResponse) GetUpserted() int64 {
	if x != nil {
		return x.Upserted
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_nucladb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_nucladb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// A search keeps vectors matching every filter it's given.
type MetadataFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // for EQ, NE and the numeric ops
	Op            FilterOp               `protobuf:"varint,3,opt,name=op,proto3,enum=nucladb.v1.FilterOp" json:"op,omitempty"`
	Values        []string               `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty"` // for IN and NOT_IN
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataFilter) Reset() {
	*x = MetadataFilter{}
	mi := &file_proto_nucladb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataFilter) ProtoMessage() {}

func (x *MetadataFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataFilter.ProtoReflect.Descriptor instead.
func (*MetadataFilter) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{10}
}

func (x *MetadataFilter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetadataFilter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *MetadataFilter) GetOp() FilterOp {
	if x != nil {
		return x.Op
	}
	return FilterOp_FILTER_OP_EQ
}

func (x *MetadataFilter) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         []float32              `protobuf:"fixed32,1,rep,packed,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Metric        DistanceMetric         `protobuf:"varint,3,opt,name=metric,proto3,enum=nucladb.v1.DistanceMetric" json:"metric,omitempty"`
	EfSearch      int32                  `protobuf:"varint,4,opt,name=ef_search,json=efSearch,proto3" json:"ef_search,omitempty"`
	Filters       []*MetadataFilter      `protobuf:"bytes,5,rep,name=filters,proto3" json:"filters,omitempty"`
	TenantId      string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_nucladb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{11}
}

func (x *SearchRequest) GetQuery() []float32 {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetMetric() DistanceMetric {
	if x != nil {
		return x.Metric
	}
	return DistanceMetric_DISTANCE_METRIC_UNSPECIFIED
}

func (x *SearchRequest) GetEfSearch() int32 {
	if x != nil {
		return x.EfSearch
	}
	return 0
}

func (x *SearchRequest) GetFilters() []*MetadataFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SearchRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ScoredVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoredVector) Reset() {
	*x = ScoredVector{}
	mi := &file_proto_nucladb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredVector) ProtoMessage() {}

func (x *ScoredVector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredVector.ProtoReflect.Descriptor instead.
func (*ScoredVector) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{12}
}

func (x *ScoredVector) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScoredVector) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoredVector) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*ScoredVector        `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_nucladb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{13}
}

func (x *SearchResponse) GetMatches() []*ScoredVector {
	if x != nil {
		return x.Matches
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_nucladb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{14}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// For cosine indexes the stored vector is scaled to unit length, so that
// is what comes back.
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        *Vector                `protobuf:"bytes,1,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_nucladb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{15}
}

func (x *GetResponse) GetVector() *Vector {
	if x != nil {
		return x.Vector
	}
	return nil
}

// List pages through a tenant's ids in ascending numeric order.
type ListRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// next_page_token from the previous response; empty for the first page.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// At most 1000; 0 means 100.
	PageSize      int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_nucladb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{16}
}

func (x *ListRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ids   []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	// Empty when there are no more pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_nucladb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{17}
}

func (x *ListResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountRequest) Reset() {
	*x = CountRequest{}
	mi := &file_proto_nucladb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRequest) ProtoMessage() {}

func (x *CountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRequest.ProtoReflect.Descriptor instead.
func (*CountRequest) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{18}
}

func (x *CountRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type CountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	mi := &file_proto_nucladb_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{19}
}

func (x *CountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Replaces the vector's whole metadata map; an empty map clears it.
type UpdateMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetadataRequest) Reset() {
	*x = UpdateMetadataRequest{}
	mi := &file_proto_nucladb_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetadataRequest) ProtoMessage() {}

func (x *UpdateMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateMetadataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMetadataRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateMetadataRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type UpdateMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetadataResponse) Reset() {
	*x = UpdateMetadataResponse{}
	mi := &file_proto_nucladb_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetadataResponse) ProtoMessage() {}

func (x *UpdateMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetadataResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetadataResponse) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{21}
}

type DeleteTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantRequest) Reset() {
	*x = DeleteTenantRequest{}
	mi := &file_proto_nucladb_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantRequest) ProtoMessage() {}

func (x *DeleteTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantRequest.ProtoReflect.Descriptor instead.
func (*DeleteTenantRequest) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DeleteTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantResponse) Reset() {
	*x = DeleteTenantResponse{}
	mi := &file_proto_nucladb_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantResponse) ProtoMessage() {}

func (x *DeleteTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantResponse.ProtoReflect.Descriptor instead.
func (*DeleteTenantResponse) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{23}
}

type SetQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Quota         *TenantQuota           `protobuf:"bytes,2,opt,name=quota,proto3" json:"quota,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetQuotaRequest) Reset() {
	*x = SetQuotaRequest{}
	mi := &file_proto_nucladb_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetQuotaRequest) ProtoMessage() {}

func (x *SetQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetQuotaRequest.ProtoReflect.Descriptor instead.
func (*SetQuotaRequest) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{24}
}

func (x *SetQuotaRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SetQuotaRequest) GetQuota() *TenantQuota {
	if x != nil {
		return x.Quota
	}
	return nil
}

type SetQuotaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetQuotaResponse) Reset() {
	*x = SetQuotaResponse{}
	mi := &file_proto_nucladb_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetQuotaResponse) ProtoMessage() {}

func (x *SetQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetQuotaResponse.ProtoReflect.Descriptor instead.
func (*SetQuotaResponse) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{25}
}

type ListTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsRequest) Reset() {
	*x = ListTenantsRequest{}
	mi := &file_proto_nucladb_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsRequest) ProtoMessage() {}

func (x *ListTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantsRequest) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{26}
}

type TenantInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	VectorCount   int64                  `protobuf:"varint,2,opt,name=vector_count,json=vectorCount,proto3" json:"vector_count,omitempty"`
	Quota         *TenantQuota           `protobuf:"bytes,3,opt,name=quota,proto3" json:"quota,omitempty"`
	Dim           int32                  `protobuf:"varint,4,opt,name=dim,proto3" json:"dim,omitempty"`
	Metric        DistanceMetric         `protobuf:"varint,5,opt,name=metric,proto3,enum=nucladb.v1.DistanceMetric" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantInfo) Reset() {
	*x = TenantInfo{}
	mi := &file_proto_nucladb_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantInfo) ProtoMessage() {}

func (x *TenantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantInfo.ProtoReflect.Descriptor instead.
func (*TenantInfo) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{27}
}

func (x *TenantInfo) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantInfo) GetVectorCount() int64 {
	if x != nil {
		return x.VectorCount
	}
	return 0
}

func (x *TenantInfo) GetQuota() *TenantQuota {
	if x != nil {
		return x.Quota
	}
	return nil
}

func (x *TenantInfo) GetDim() int32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *TenantInfo) GetMetric() DistanceMetric {
	if x != nil {
		return x.Metric
	}
	return DistanceMetric_DISTANCE_METRIC_UNSPECIFIED
}

type ListTenantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*TenantInfo          `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsResponse) Reset() {
	*x = ListTenantsResponse{}
	mi := &file_proto_nucladb_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsResponse) ProtoMessage() {}

func (x *ListTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nucladb_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsResponse.ProtoReflect.Descriptor instead.
func (*ListTenantsResponse) Descriptor() ([]byte, []int) {
	return file_proto_nucladb_proto_rawDescGZIP(), []int{28}
}

func (x *ListTenantsResponse) GetTenants() []*TenantInfo {
	if x != nil {
		return x.Tenants
	}
	return nil
}

var File_proto_nucladb_proto protoreflect.FileDescriptor

const file_proto_nucladb_proto_rawDesc = "" +
	"\n" +
	"\x13proto/nucladb.proto\x12\n" +
	"nucladb.v1\"G\n" +
	"\vTenantQuota\x12\x1f\n" +
	"\vmax_vectors\x18\x01 \x01(\x03R\n" +
	"maxVectors\x12\x17\n" +
	"\amax_qps\x18\x02 \x01(\x01R\x06maxQps\"\xa7\x01\n" +
	"\x13CreateTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12-\n" +
	"\x05quota\x18\x02 \x01(\v2\x17.nucladb.v1.TenantQuotaR\x05quota\x12\x10\n" +
	"\x03dim\x18\x03 \x01(\x05R\x03dim\x122\n" +
	"\x06metric\x18\x04 \x01(\x0e2\x1a.nucladb.v1.DistanceMetricR\x06metric\"\x16\n" +
	"\x14CreateTenantResponse\"\xc8\x01\n" +
	"\x06Vector\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x02R\x06values\x12<\n" +
	"\bmetadata\x18\x03 \x03(\v2 .nucladb.v1.Vector.MetadataEntryR\bmetadata\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\rInsertRequest\x12*\n" +
	"\x06vector\x18\x01 \x01(\v2\x12.nucladb.v1.VectorR\x06vector\" \n" +
	"\x0eInsertResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x12BatchUpsertRequest\x12,\n" +
	"\avectors\x18\x01 \x03(\v2\x12.nucladb.v1.VectorR\avectors\"1\n" +
	"\x13BatchUpsertResponse\x12\x1a\n" +
	"\bupserted\x18\x01 \x01(\x03R\bupserted\"<\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"v\n" +
	"\x0eMetadataFilter\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12$\n" +
	"\x02op\x18\x03 \x01(\x0e2\x14.nucladb.v1.FilterOpR\x02op\x12\x16\n" +
	"\x06values\x18\x04 \x03(\tR\x06values\"\xde\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x03(\x02R\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x122\n" +
	"\x06metric\x18\x03 \x01(\x0e2\x1a.nucladb.v1.DistanceMetricR\x06metric\x12\x1b\n" +
	"\tef_search\x18\x04 \x01(\x05R\befSearch\x124\n" +
	"\afilters\x18\x05 \x03(\v2\x1a.nucladb.v1.MetadataFilterR\afilters\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\"\xb5\x01\n" +
	"\fScoredVector\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12B\n" +
	"\bmetadata\x18\x03 \x03(\v2&.nucladb.v1.ScoredVector.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x0eSearchResponse\x122\n" +
	"\amatches\x18\x01 \x03(\v2\x18.nucladb.v1.ScoredVectorR\amatches\"9\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"9\n" +
	"\vGetResponse\x12*\n" +
	"\x06vector\x18\x01 \x01(\v2\x12.nucladb.v1.VectorR\x06vector\"f\n" +
	"\vListRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"H\n" +
	"\fListResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"+\n" +
	"\fCountRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"%\n" +
	"\rCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"\xce\x01\n" +
	"\x15UpdateMetadataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12K\n" +
	"\bmetadata\x18\x02 \x03(\v2/.nucladb.v1.UpdateMetadataRequest.MetadataEntryR\bmetadata\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x18\n" +
	"\x16UpdateMetadataResponse\"2\n" +
	"\x13DeleteTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"\x16\n" +
	"\x14DeleteTenantResponse\"]\n" +
	"\x0fSetQuotaRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12-\n" +
	"\x05quota\x18\x02 \x01(\v2\x17.nucladb.v1.TenantQuotaR\x05quota\"\x12\n" +
	"\x10SetQuotaResponse\"\x14\n" +
	"\x12ListTenantsRequest\"\xc1\x01\n" +
	"\n" +
	"TenantInfo\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fvector_count\x18\x02 \x01(\x03R\vvectorCount\x12-\n" +
	"\x05quota\x18\x03 \x01(\v2\x17.nucladb.v1.TenantQuotaR\x05quota\x12\x10\n" +
	"\x03dim\x18\x04 \x01(\x05R\x03dim\x122\n" +
	"\x06metric\x18\x05 \x01(\x0e2\x1a.nucladb.v1.DistanceMetricR\x06metric\"G\n" +
	"\x13ListTenantsResponse\x120\n" +
	"\atenants\x18\x01 \x03(\v2\x16.nucladb.v1.TenantInfoR\atenants*~\n" +
	"\x0eDistanceMetric\x12\x1f\n" +
	"\x1bDISTANCE_METRIC_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DISTANCE_METRIC_COSINE\x10\x01\x12\x16\n" +
	"\x12DISTANCE_METRIC_L2\x10\x02\x12\x17\n" +
	"\x13DISTANCE_METRIC_DOT\x10\x03*\xb6\x01\n" +
	"\bFilterOp\x12\x10\n" +
	"\fFILTER_OP_EQ\x10\x00\x12\x10\n" +
	"\fFILTER_OP_NE\x10\x01\x12\x10\n" +
	"\fFILTER_OP_IN\x10\x02\x12\x14\n" +
	"\x10FILTER_OP_NOT_IN\x10\x03\x12\x10\n" +
	"\fFILTER_OP_GT\x10\x04\x12\x11\n" +
	"\rFILTER_OP_GTE\x10\x05\x12\x10\n" +
	"\fFILTER_OP_LT\x10\x06\x12\x11\n" +
	"\rFILTER_OP_LTE\x10\a\x12\x14\n" +
	"\x10FILTER_OP_EXISTS\x10\b2\xe3\x06\n" +
	"\aNuclaDB\x12Q\n" +
	"\fCreateTenant\x12\x1f.nucladb.v1.CreateTenantRequest\x1a .nucladb.v1.CreateTenantResponse\x12?\n" +
	"\x06Insert\x12\x19.nucladb.v1.InsertRequest\x1a\x1a.nucladb.v1.InsertResponse\x12N\n" +
	"\vBatchUpsert\x12\x1e.nucladb.v1.BatchUpsertRequest\x1a\x1f.nucladb.v1.BatchUpsertResponse\x12?\n" +
	"\x06Delete\x12\x19.nucladb.v1.DeleteRequest\x1a\x1a.nucladb.v1.DeleteResponse\x12?\n" +
	"\x06Search\x12\x19.nucladb.v1.SearchRequest\x1a\x1a.nucladb.v1.SearchResponse\x126\n" +
	"\x03Get\x12\x16.nucladb.v1.GetRequest\x1a\x17.nucladb.v1.GetResponse\x129\n" +
	"\x04List\x12\x17.nucladb.v1.ListRequest\x1a\x18.nucladb.v1.ListResponse\x12<\n" +
	"\x05Count\x12\x18.nucladb.v1.CountRequest\x1a\x19.nucladb.v1.CountResponse\x12W\n" +
	"\x0eUpdateMetadata\x12!.nucladb.v1.UpdateMetadataRequest\x1a\".nucladb.v1.UpdateMetadataResponse\x12Q\n" +
	"\fDeleteTenant\x12\x1f.nucladb.v1.DeleteTenantRequest\x1a .nucladb.v1.DeleteTenantResponse\x12E\n" +
	"\bSetQuota\x12\x1b.nucladb.v1.SetQuotaRequest\x1a\x1c.nucladb.v1.SetQuotaResponse\x12N\n" +
	"\vListTenants\x12\x1e.nucladb.v1.ListTenantsRequest\x1a\x1f.nucladb.v1.ListTenantsResponseB0Z.github.com/Rakshit-gen/nucladb/proto/nucladbv1b\x06proto3"

var (
	file_proto_nucladb_proto_rawDescOnce sync.Once
	file_proto_nucladb_proto_rawDescData []byte
)

func file_proto_nucladb_proto_rawDescGZIP() []byte {
	file_proto_nucladb_proto_rawDescOnce.Do(func() {
		file_proto_nucladb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_nucladb_proto_rawDesc), len(file_proto_nucladb_proto_rawDesc)))
	})
	return file_proto_nucladb_proto_rawDescData
}

var file_proto_nucladb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_nucladb_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_proto_nucladb_proto_goTypes = []any{
	(DistanceMetric)(0),            // 0: nucladb.v1.DistanceMetric
	(FilterOp)(0),                  // 1: nucladb.v1.FilterOp
	(*TenantQuota)(nil),            // 2: nucladb.v1.TenantQuota
	(*CreateTenantRequest)(nil),    // 3: nucladb.v1.CreateTenantRequest
	(*CreateTenantResponse)(nil),   // 4: nucladb.v1.CreateTenantResponse
	(*Vector)(nil),                 // 5: nucladb.v1.Vector
	(*InsertRequest)(nil),          // 6: nucladb.v1.InsertRequest
	(*InsertResponse)(nil),         // 7: nucladb.v1.InsertResponse
	(*BatchUpsertRequest)(nil),     // 8: nucladb.v1.BatchUpsertRequest
	(*BatchUpsertResponse)(nil),    // 9: nucladb.v1.BatchUpsertResponse
	(*DeleteRequest)(nil),          // 10: nucladb.v1.DeleteRequest
	(*DeleteResponse)(nil),         // 11: nucladb.v1.DeleteResponse
	(*MetadataFilter)(nil),         // 12: nucladb.v1.MetadataFilter
	(*SearchRequest)(nil),          // 13: nucladb.v1.SearchRequest
	(*ScoredVector)(nil),           // 14: nucladb.v1.ScoredVector
	(*SearchResponse)(nil),         // 15: nucladb.v1.SearchResponse
	(*GetRequest)(nil),             // 16: nucladb.v1.GetRequest
	(*GetResponse)(nil),            // 17: nucladb.v1.GetResponse
	(*ListRequest)(nil),            // 18: nucladb.v1.ListRequest
	(*ListResponse)(nil),           // 19: nucladb.v1.ListResponse
	(*CountRequest)(nil),           // 20: nucladb.v1.CountRequest
	(*CountResponse)(nil),          // 21: nucladb.v1.CountResponse
	(*UpdateMetadataRequest)(nil),  // 22: nucladb.v1.UpdateMetadataRequest
	(*UpdateMetadataResponse)(nil), // 23: nucladb.v1.UpdateMetadataResponse
	(*DeleteTenantRequest)(nil),    // 24: nucladb.v1.DeleteTenantRequest
	(*DeleteTenantResponse)(nil),   // 25: nucladb.v1.DeleteTenantResponse
	(*SetQuotaRequest)(nil),        // 26: nucladb.v1.SetQuotaRequest
	(*SetQuotaResponse)(nil),       // 27: nucladb.v1.SetQuotaResponse
	(*ListTenantsRequest)(nil),     // 28: nucladb.v1.ListTenantsRequest
	(*TenantInfo)(nil),             // 29: nucladb.v1.TenantInfo
	(*ListTenantsResponse)(nil),    // 30: nucladb.v1.ListTenantsResponse
	nil,                            // 31: nucladb.v1.Vector.MetadataEntry
	nil,                            // 32: nucladb.v1.ScoredVector.MetadataEntry
	nil,                            // 33: nucladb.v1.UpdateMetadataRequest.MetadataEntry
}
var file_proto_nucladb_proto_depIdxs = []int32{
	2,  // 0: nucladb.v1.CreateTenantRequest.quota:type_name -> nucladb.v1.TenantQuota
	0,  // 1: nucladb.v1.CreateTenantRequest.metric:type_name -> nucladb.v1.DistanceMetric
	31, // 2: nucladb.v1.Vector.metadata:type_name -> nucladb.v1.Vector.MetadataEntry
	5,  // 3: nucladb.v1.InsertRequest.vector:type_name -> nucladb.v1.Vector
	5,  // 4: nucladb.v1.BatchUpsertRequest.vectors:type_name -> nucladb.v1.Vector
	1,  // 5: nucladb.v1.MetadataFilter.op:type_name -> nucladb.v1.FilterOp
	0,  // 6: nucladb.v1.SearchRequest.metric:type_name -> nucladb.v1.DistanceMetric
	12, // 7: nucladb.v1.SearchRequest.filters:type_name -> nucladb.v1.MetadataFilter
	32, // 8: nucladb.v1.ScoredVector.metadata:type_name -> nucladb.v1.ScoredVector.MetadataEntry
	14, // 9: nucladb.v1.SearchResponse.matches:type_name -> nucladb.v1.ScoredVector
	5,  // 10: nucladb.v1.GetResponse.vector:type_name -> nucladb.v1.Vector
	33, // 11: nucladb.v1.UpdateMetadataRequest.metadata:type_name -> nucladb.v1.UpdateMetadataRequest.MetadataEntry
	2,  // 12: nucladb.v1.SetQuotaRequest.quota:type_name -> nucladb.v1.TenantQuota
	2,  // 13: nucladb.v1.TenantInfo.quota:type_name -> nucladb.v1.TenantQuota
	0,  // 14: nucladb.v1.TenantInfo.metric:type_name -> nucladb.v1.DistanceMetric
	29, // 15: nucladb.v1.ListTenantsResponse.tenants:type_name -> nucladb.v1.TenantInfo
	3,  // 16: nucladb.v1.NuclaDB.CreateTenant:input_type -> nucladb.v1.CreateTenantRequest
	6,  // 17: nucladb.v1.NuclaDB.Insert:input_type -> nucladb.v1.InsertRequest
	8,  // 18: nucladb.v1.NuclaDB.BatchUpsert:input_type -> nucladb.v1.BatchUpsertRequest
	10, // 19: nucladb.v1.NuclaDB.Delete:input_type -> nucladb.v1.DeleteRequest
	13, // 20: nucladb.v1.NuclaDB.Search:input_type -> nucladb.v1.SearchRequest
	16, // 21: nucladb.v1.NuclaDB.Get:input_type -> nucladb.v1.GetRequest
	18, // 22: nucladb.v1.NuclaDB.List:input_type -> nucladb.v1.ListRequest
	20, // 23: nucladb.v1.NuclaDB.Count:input_type -> nucladb.v1.CountRequest
	22, // 24: nucladb.v1.NuclaDB.UpdateMetadata:input_type -> nucladb.v1.UpdateMetadataRequest
	24, // 25: nucladb.v1.NuclaDB.DeleteTenant:input_type -> nucladb.v1.DeleteTenantRequest
	26, // 26: nucladb.v1.NuclaDB.SetQuota:input_type -> nucladb.v1.SetQuotaRequest
	28, // 27: nucladb.v1.NuclaDB.ListTenants:input_type -> nucladb.v1.ListTenantsRequest
	4,  // 28: nucladb.v1.NuclaDB.CreateTenant:output_type -> nucladb.v1.CreateTenantResponse
	7,  // 29: nucladb.v1.NuclaDB.Insert:output_type -> nucladb.v1.InsertResponse
	9,  // 30: nucladb.v1.NuclaDB.BatchUpsert:output_type -> nucladb.v1.BatchUpsertResponse
	11, // 31: nucladb.v1.NuclaDB.Delete:output_type -> nucladb.v1.DeleteResponse
	15, // 32: nucladb.v1.NuclaDB.Search:output_type -> nucladb.v1.SearchResponse
	17, // 33: nucladb.v1.NuclaDB.Get:output_type -> nucladb.v1.GetResponse
	19, // 34: nucladb.v1.NuclaDB.List:output_type -> nucladb.v1.ListResponse
	21, // 35: nucladb.v1.NuclaDB.Count:output_type -> nucladb.v1.CountResponse
	23, // 36: nucladb.v1.NuclaDB.UpdateMetadata:output_type -> nucladb.v1.UpdateMetadataResponse
	25, // 37: nucladb.v1.NuclaDB.DeleteTenant:output_type -> nucladb.v1.DeleteTenantResponse
	27, // 38: nucladb.v1.NuclaDB.SetQuota:output_type -> nucladb.v1.SetQuotaResponse
	30, // 39: nucladb.v1.NuclaDB.ListTenants:output_type -> nucladb.v1.ListTenantsResponse
	28, // [28:40] is the sub-list for method output_type
	16, // [16:28] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_nucladb_proto_init() }
func file_proto_nucladb_proto_init() {
	if File_proto_nucladb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_nucladb_proto_rawDesc), len(file_proto_nucladb_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_nucladb_proto_goTypes,
		DependencyIndexes: file_proto_nucladb_proto_depIdxs,
		EnumInfos:         file_proto_nucladb_proto_enumTypes,
		MessageInfos:      file_proto_nucladb_proto_msgTypes,
	}.Build()
	File_proto_nucladb_proto = out.File
	file_proto_nucladb_proto_goTypes = nil
	file_proto_nucladb_proto_depIdxs = nil
}
