# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import nucladb_pb2 as nucladb__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nucladb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NuclaDBStub:
    """NuclaDB is a vector similarity search engine: insert vectors with an
    optional metadata payload, then search for the nearest neighbors of a
    query vector under a chosen distance metric.

    Every data RPC is tenant-scoped: each tenant_id gets an isolated index
    (its own graph, WAL, and snapshot files on disk), with an independent
    storage quota and request-rate limit. An empty tenant_id resolves to a
    reserved "default" tenant with no quota, so existing single-tenant
    usage needs no changes.

    REST is exposed separately via a hand-written gateway in
    internal/api/gateway rather than google.api.http annotations, to avoid
    vendoring the full googleapis proto tree.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTenant = channel.unary_unary(
                '/nucladb.v1.NuclaDB/CreateTenant',
                request_serializer=nucladb__pb2.CreateTenantRequest.SerializeToString,
                response_deserializer=nucladb__pb2.CreateTenantResponse.FromString,
                _registered_method=True)
        self.Insert = channel.unary_unary(
                '/nucladb.v1.NuclaDB/Insert',
                request_serializer=nucladb__pb2.InsertRequest.SerializeToString,
                response_deserializer=nucladb__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.BatchUpsert = channel.unary_unary(
                '/nucladb.v1.NuclaDB/BatchUpsert',
                request_serializer=nucladb__pb2.BatchUpsertRequest.SerializeToString,
                response_deserializer=nucladb__pb2.BatchUpsertResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/nucladb.v1.NuclaDB/Delete',
                request_serializer=nucladb__pb2.DeleteRequest.SerializeToString,
                response_deserializer=nucladb__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/nucladb.v1.NuclaDB/Search',
                request_serializer=nucladb__pb2.SearchRequest.SerializeToString,
                response_deserializer=nucladb__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/nucladb.v1.NuclaDB/Get',
                request_serializer=nucladb__pb2.GetRequest.SerializeToString,
                response_deserializer=nucladb__pb2.GetResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/nucladb.v1.NuclaDB/List',
                request_serializer=nucladb__pb2.ListRequest.SerializeToString,
                response_deserializer=nucladb__pb2.ListResponse.FromString,
                _registered_method=True)
        self.Count = channel.unary_unary(
                '/nucladb.v1.NuclaDB/Count',
                request_serializer=nucladb__pb2.CountRequest.SerializeToString,
                response_deserializer=nucladb__pb2.CountResponse.FromString,
                _registered_method=True)
        self.UpdateMetadata = channel.unary_unary(
                '/nucladb.v1.NuclaDB/UpdateMetadata',
                request_serializer=nucladb__pb2.UpdateMetadataRequest.SerializeToString,
                response_deserializer=nucladb__pb2.UpdateMetadataResponse.FromString,
                _registered_method=True)
        self.DeleteTenant = channel.unary_unary(
                '/nucladb.v1.NuclaDB/DeleteTenant',
                request_serializer=nucladb__pb2.DeleteTenantRequest.SerializeToString,
                response_deserializer=nucladb__pb2.DeleteTenantResponse.FromString,
                _registered_method=True)
        self.SetQuota = channel.unary_unary(
                '/nucladb.v1.NuclaDB/SetQuota',
                request_serializer=nucladb__pb2.SetQuotaRequest.SerializeToString,
                response_deserializer=nucladb__pb2.SetQuotaResponse.FromString,
                _registered_method=True)
        self.ListTenants = channel.unary_unary(
                '/nucladb.v1.NuclaDB/ListTenants',
                request_serializer=nucladb__pb2.ListTenantsRequest.SerializeToString,
                response_deserializer=nucladb__pb2.ListTenantsResponse.FromString,
                _registered_method=True)


class NuclaDBServicer:
    """NuclaDB is a vector similarity search engine: insert vectors with an
    optional metadata payload, then search for the nearest neighbors of a
    query vector under a chosen distance metric.

    Every data RPC is tenant-scoped: each tenant_id gets an isolated index
    (its own graph, WAL, and snapshot files on disk), with an independent
    storage quota and request-rate limit. An empty tenant_id resolves to a
    reserved "default" tenant with no quota, so existing single-tenant
    usage needs no changes.

    REST is exposed separately via a hand-written gateway in
    internal/api/gateway rather than google.api.http annotations, to avoid
    vendoring the full googleapis proto tree.
    """

    def CreateTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchUpsert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Count(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetQuota(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTenants(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NuclaDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTenant,
                    request_deserializer=nucladb__pb2.CreateTenantRequest.FromString,
                    response_serializer=nucladb__pb2.CreateTenantResponse.SerializeToString,
            ),
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=nucladb__pb2.InsertRequest.FromString,
                    response_serializer=nucladb__pb2.InsertResponse.SerializeToString,
            ),
            'BatchUpsert': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchUpsert,
                    request_deserializer=nucladb__pb2.BatchUpsertRequest.FromString,
                    response_serializer=nucladb__pb2.BatchUpsertResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=nucladb__pb2.DeleteRequest.FromString,
                    response_serializer=nucladb__pb2.DeleteResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=nucladb__pb2.SearchRequest.FromString,
                    response_serializer=nucladb__pb2.SearchResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=nucladb__pb2.GetRequest.FromString,
                    response_serializer=nucladb__pb2.GetResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=nucladb__pb2.ListRequest.FromString,
                    response_serializer=nucladb__pb2.ListResponse.SerializeToString,
            ),
            'Count': grpc.unary_unary_rpc_method_handler(
                    servicer.Count,
                    request_deserializer=nucladb__pb2.CountRequest.FromString,
                    response_serializer=nucladb__pb2.CountResponse.SerializeToString,
            ),
            'UpdateMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMetadata,
                    request_deserializer=nucladb__pb2.UpdateMetadataRequest.FromString,
                    response_serializer=nucladb__pb2.UpdateMetadataResponse.SerializeToString,
            ),
            'DeleteTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTenant,
                    request_deserializer=nucladb__pb2.DeleteTenantRequest.FromString,
                    response_serializer=nucladb__pb2.DeleteTenantResponse.SerializeToString,
            ),
            'SetQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.SetQuota,
                    request_deserializer=nucladb__pb2.SetQuotaRequest.FromString,
                    response_serializer=nucladb__pb2.SetQuotaResponse.SerializeToString,
            ),
            'ListTenants': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTenants,
                    request_deserializer=nucladb__pb2.ListTenantsRequest.FromString,
                    response_serializer=nucladb__pb2.ListTenantsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nucladb.v1.NuclaDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nucladb.v1.NuclaDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NuclaDB:
    """NuclaDB is a vector similarity search engine: insert vectors with an
    optional metadata payload, then search for the nearest neighbors of a
    query vector under a chosen distance metric.

    Every data RPC is tenant-scoped: each tenant_id gets an isolated index
    (its own graph, WAL, and snapshot files on disk), with an independent
    storage quota and request-rate limit. An empty tenant_id resolves to a
    reserved "default" tenant with no quota, so existing single-tenant
    usage needs no changes.

    REST is exposed separately via a hand-written gateway in
    internal/api/gateway rather than google.api.http annotations, to avoid
    vendoring the full googleapis proto tree.
    """

    @staticmethod
    def CreateTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nucladb.v1.NuclaDB/CreateTenant',
            nucladb__pb2.CreateTenantRequest.SerializeToString,
            nucladb__pb2.CreateTenantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nucladb.v1.NuclaDB/Insert',
            nucladb__pb2.InsertRequest.SerializeToString,
            nucladb__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchUpsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nucladb.v1.NuclaDB/BatchUpsert',
            nucladb__pb2.BatchUpsertRequest.SerializeToString,
            nucladb__pb2.BatchUpsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nucladb.v1.NuclaDB/Delete',
            nucladb__pb2.DeleteRequest.SerializeToString,
            nucladb__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nucladb.v1.NuclaDB/Search',
            nucladb__pb2.SearchRequest.SerializeToString,
            nucladb__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nucladb.v1.NuclaDB/Get',
            nucladb__pb2.GetRequest.SerializeToString,
            nucladb__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nucladb.v1.NuclaDB/List',
            nucladb__pb2.ListRequest.SerializeToString,
            nucladb__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Count(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nucladb.v1.NuclaDB/Count',
            nucladb__pb2.CountRequest.SerializeToString,
            nucladb__pb2.CountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nucladb.v1.NuclaDB/UpdateMetadata',
            nucladb__pb2.UpdateMetadataRequest.SerializeToString,
            nucladb__pb2.UpdateMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nucladb.v1.NuclaDB/DeleteTenant',
            nucladb__pb2.DeleteTenantRequest.SerializeToString,
            nucladb__pb2.DeleteTenantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nucladb.v1.NuclaDB/SetQuota',
            nucladb__pb2.SetQuotaRequest.SerializeToString,
            nucladb__pb2.SetQuotaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTenants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nucladb.v1.NuclaDB/ListTenants',
            nucladb__pb2.ListTenantsRequest.SerializeToString,
            nucladb__pb2.ListTenantsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
